version: '3.4'

services:
  srv:
    depends_on:
    - db
    networks:
    - backend
    - frontend
    container_name: gst-server
  db:
    volumes:
    - gstore:/data/db
    - gstore:/data/configdb
    networks:
    - backend
    container_name: gst-db
volumes:
  gstore:
networks:
  frontend:
  backend: