version: '3.4'

services:
  # web:
  #   environment:
  #     TZ: Europe/Rome
  #   ports:
  #     - "8080:80"
  srv:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: gstore
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Staging
      TZ: Europe/Rome
    ports:
    - "5000:5000"
  db:
    environment:
      TZ: Europe/Rome
    ports:
    - "27017:27017"
    volumes:
    - ./db:/docker-entrypoint-initdb.d