version: '3.4'

services:
  app:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: antdimot/gstore
    links: 
    - db
    depends_on:
    - db
    networks:
    - backend
    - frontend
    volumes:
    - appdata:/app/data
  db:
    image: mongo:4
    volumes:
    - database:/data/db
    - database:/data/configdb
    networks:
    - backend
volumes:
  database:
  appdata:
networks:
  frontend:
  backend: