version: '3.4'

services:
  # web:
  #   links: 
  #   - srv
  #   depends_on:
  #   - srv
  #   networks:
  #   - frontend
  #   container_name: gstore-web
  srv:
    links: 
    - db
    depends_on:
    - db
    networks:
    - backend
    - frontend
    container_name: gstore-server
  db:
    image: mongo:4
    volumes:
    - gstore-db:/data/db
    - gstore-db:/data/configdb
    networks:
    - backend
    container_name: gstore-db
volumes:
  gstore-db:
networks:
  frontend:
  backend: