version: '3.4'

services:
  srv:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: gstore
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Staging
      TZ: Europe/Rome
    ports:
    - "5000:5000"
  db:
    image: mongo:4
    environment:
      TZ: Europe/Rome
    ports:
    - "27017:27017"
    volumes:
    - ./db:/docker-entrypoint-initdb.d # this is for populating db with test data only, remove this line for production environment