version: '3.4'

services:
  app:
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
      TZ: Europe/Rome
    ports:
    - "5000:5000"
  db:
    restart: always
    environment:
      TZ: Europe/Rome
    volumes:
    - ./src/db:/docker-entrypoint-initdb.d