version: '3.4'

services:
  app:
    image: antdimot/gstore
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
      TZ: Europe/Rome
    ports:
    - "5000:5000"
    links: 
    - db
    depends_on:
    - db
    volumes:
    - appdata:/app/data
    networks:
    - backend
    - frontend
  db:
    image: mongo:4.0
    restart: always
    volumes:
    - database:/data/db
    - database:/data/configdb
    - appdata:/docker-entrypoint-initdb.d/data.js
    networks:
    - backend
volumes:
  database:
  appdata:
networks:
  frontend:
  backend: