POST http://localhost:5000/api/v1.0/user/authenticate HTTP/1.1
content-type: application/json
content-disposition: form-data

{
    "username": "antonio.dimotta@gmail.com",
    "password": "P@ssw0rd"
}

###

GET http://localhost:5000/api/v1.0/geodata/location?lon=14.2749&lat=40.850506&distance=0.5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFudG9uaW8uZGltb3R0YUBnbWFpbC5jb20iLCJVc2VySWQiOiI1YWEzYTZjMzYwZDUzYzBlNTU2NWYzYTkiLCJVc2VyQXV0aHoiOiJhZG1pbixyZWFkZXIsd3JpdGVyIiwibmJmIjoxNTM4MDU4OTMyLCJleHAiOjE1MzgwNjEzMzIsImlhdCI6MTUzODA1ODkzMiwiaXNzIjoiR1N0b3JlSXNzdWVyIiwiYXVkIjoiR1N0b3JlQXVkaWVuY2UifQ.l_vvW41i0Fk8z3XYqHHw8smWAegaQUcuKJ4Yr20xHBY
