version: '3.4'

services:
  gstore-api:
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Staging
      TZ: Europe/Rome
    ports:
    - "5000:5000"
  gstore-db:
    environment:
      TZ: Europe/Rome
    ports:
    - "27017:27017"
    volumes:
    - ./db:/docker-entrypoint-initdb.d/data.js