version: '3.4'

services:
  gstore-api:
    build:
      context: .
      dockerfile: GStore.API/Dockerfile
    image: antdimot/gstore
    links: 
    - gstore-db
    depends_on:
    - gstore-db
    volumes:
    - gstore-vol-api:/app
    networks:
    - backend
    - frontend
  gstore-db:
    image: mongo:4.0
    volumes:
    - gstore-vol-db:/data/db
    - gstore-vol-db:/data/configdb
    networks:
    - backend
volumes:
  gstore-vol-db:
  gstore-vol-api:
networks:
  frontend:
  backend: