version: '3.4'

services:
  gstore-api:
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
      TZ: Europe/Rome
    ports:
    - "5000:5000"
  gstore-db:
    restart: always
    environment:
      TZ: Europe/Rome
    volumes:
    - gstore-vol-api:/docker-entrypoint-initdb.d/data.js