name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: gstore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
  
    - name: Log into registry
      run:  echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push image
      run:
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

        VERSION=latest
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        
        docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
