name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: antdimot/gstore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build image
      run:
        docker build ./src/server -f ./src/server/Dockerfile -t $IMAGE_NAME
  
    - name: Log into registry
      run:  docker login --username antdimot --password ${{ secrets.GITHUB_WORKFLOW_TOKEN }}

    - name: Push image
      run:
        docker push $IMAGE_NAME
