name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: antdimot/gstore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
  
    - name: Log into registry
      run:  echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push image
      run:
        echo $IMAGE_NAME

        docker push $IMAGE_NAME:latest
